version: '3'
services:
  db:
    image: mongo
    volumes:
      - ./db:/data/db
  server:
    depends_on:
      - db
    env_file: .env
    build:
      context: ./bin
      dockerfile: server.dockerfile
    ports:
      - "${SERVER_PORT}:1337"
    volumes:
      - ./server:/app/server
      - ./bin/server.sh:/app/entrypoint.sh
      - ./bin/strapi.exp:/app/strapi.exp
  client:
    depends_on:
      - server
    env_file: .env
    build:
      context: ./bin
      dockerfile: client.dockerfile
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - ./client:/app/client
      - ./bin/client.sh:/app/entrypoint.sh
      - ./bin/vue-cli.exp:/app/vue-cli.exp
